# permissions for end users to edit dockers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: docker-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: docker-operator
    app.kubernetes.io/part-of: docker-operator
    app.kubernetes.io/managed-by: kustomize
  name: docker-editor-role
rules:
- apiGroups:
  - container.terraform.io
  resources:
  - dockers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.terraform.io
  resources:
  - dockers/status
  verbs:
  - get
