name: build

on:
  workflow_dispatch:

env:
  PKG_NAME: "docker-operator"

jobs:
  set-product-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
      - name: Set product version
        uses: hashicorp/actions-set-product-version@06bddb8ee70f0dda2e21c39b5f0913d36cc9d657 # v1
      - name: Validate
        run: |
          env
