name: Scan Docker Image

on:
  workflow_dispatch:

env:
  DOCKER_HUB_REPO: arybolovlev/docker-operator
  RELEASE_NOTES: /tmp/release-notes.txt

jobs:
  release-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=semver,pattern={{version}}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: ${{ steps.meta.outputs.tags }}
