name: Build and Publish Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  DOCKER_HUB_REPO: arybolovlev/docker-operator
  RELEASE_NOTES: /tmp/release-notes.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Release Notes
        # Fetch CHANGELOG.md contents up to Git tag prior to this release, skipping top two lines
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > ${{ env.RELEASE_NOTES }}
        
      - name: Docker image tag
        env:
          TAG: ${{ github.ref_name }}
        run: |
          echo "DOCKER_IMAGE_TAG=${TAG#v}" >> $GITHUB_ENV
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: release --skip-sign --release-notes ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.DOCKER_IMAGE_TAG }},${{ env.DOCKER_HUB_REPO }}:latest
