name: Scan Docker Image

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: docker-operator

jobs:
  release-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,format=long
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and load Docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          format: table
          image-ref: ${{ steps.meta.outputs.tags }}
          exit-code: '1'
