name: Tag release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version/VERSION
jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Find current version
        run: |
          echo "VERSION=$(cat version/VERSION)" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag v$VERSION
          git push --tags
